In [1]:
# Загрузка библиотек
import numpy as np # для работы с массивами
import pandas as pd # для работы с DataFrame 
from sklearn import datasets # для импорта данных
import seaborn as sns # для визуализации статистических данных
import matplotlib.pyplot as plt # для построения графиков

In [12]:
# создадим вырожденную матрицу А
A = np.array([
    [1, 2], 
    [-1, 0], 
    [2, 1]]
)
y = np.array([1, 1])
print(A)
print(y)
A@y



[[ 1  2]
 [-1  0]
 [ 2  1]]
[1 1]


array([ 3, -1,  3])

In [22]:
v = np.array([1, 2, 3])
F = np.array([
    [1, 0, 0], 
    [0, 0, 1], 
    [0, -1, 0]]
)

In [24]:
# Умножение матрицы на вектор
image_v = np.dot(F, v)
print(image_v)

# Вычисление длины вектора image_v
length = np.linalg.norm(image_v)
print(length)

# Вычисление длины вектора v
length_v = np.linalg.norm(v)
print(length_v)

[ 1  3 -2]
3.7416573867739413
3.7416573867739413


In [25]:
u = np.array([1, -1])
v = np.array([1, 1])
F = np.array([
    [2, 1], 
    [1, 2]]
)

image_v = np.dot(F, v)
image_u = np.dot(F, u)

print(f'image_v = {image_v}')
print(f'image_u = {image_u}')

image_v = [3 3]
image_u = [ 1 -1]


In [26]:
# Вычисление длины вектора v
length_v = np.linalg.norm(v)

# Вычисление длины вектора u
length_u = np.linalg.norm(u)

# Вычисление длины вектора image_v
length_image_v = np.linalg.norm(image_v)

# Вычисление длины вектора image_u
length_image_u = np.linalg.norm(image_u)

print(f'length_v = {length_v}')
print(f'length_u = {length_u}')
print(f'length_image_v = {length_image_v}')
print(f'length_image_u = {length_image_u}')

length_v = 1.4142135623730951
length_u = 1.4142135623730951
length_image_v = 4.242640687119285
length_image_u = 1.4142135623730951


In [28]:
# Создание векторов
u = np.array([1, -1])
v = np.array([1, 1])

# Создание матрицы оператора
F = np.array([
    [2, 1],
    [1, 2]
])

# Вычисление суммы векторов
sum_uv = u + v
print(f'sum_uv = {sum_uv}')

# Проверка условия для собственного вектора
result = np.dot(F, sum_uv)
print(result)

sum_uv = [2 0]
[4 2]


In [32]:
print(2*sum_uv)

[4 0]


In [29]:
result = np.dot(F, u)
print(result)

[ 1 -1]


In [30]:
print(5*u)

[ 5 -5]


In [31]:
print(1*u)

[ 1 -1]


In [33]:
dot_product = np.dot(u, v)
print(dot_product)

0


In [34]:
F = np.array([
    [7, 2],
    [1, 8]
])

np.linalg.det(F)

np.float64(54.00000000000001)

In [35]:
u = np.array([-2, 1])
v = np.array([-1, 1])

np.dot(u, v)

np.int64(3)

In [36]:
u = np.array([-2, 1])
v = np.array([1, 1])

np.dot(u, v)

np.int64(-1)

In [37]:
u = np.array([2, -1])
v = np.array([1, 1])

np.dot(u, v)

np.int64(1)

In [38]:
u = np.array([-1, 1])
v = np.array([1, 1])

np.dot(u, v)

np.int64(0)

In [39]:
# Характеристическое уравнение (собственные числа)
eigenvalues = np.linalg.eigvals(F)
print(eigenvalues)

[6. 9.]


In [40]:
# Матрица F
F = np.array([
    [7, 2],
    [1, 8]
])

# Векторы для проверки
u = np.array([-2, 1])
v = np.array([1, 1])

# Собственные числа
lambda_u = 6
lambda_v = 9

# Проверка уравнения для собственного вектора u
result_u = np.dot(F, u)
expected_u = lambda_u * u

print("Проверка для u:")
print("Результат:", result_u)
print("Ожидаемый результат:", expected_u)

# Проверка уравнения для собственного вектора v
result_v = np.dot(F, v)
expected_v = lambda_v * v

print("\nПроверка для v:")
print("Результат:", result_v)
print("Ожидаемый результат:", expected_v)

Проверка для u:
Результат: [-12   6]
Ожидаемый результат: [-12   6]

Проверка для v:
Результат: [9 9]
Ожидаемый результат: [9 9]


In [44]:
# Матрица F
F = np.array([
    [-7, 6],
    [-12, 11]
])

# Векторы для проверки
v = np.array([1, 2])
u = np.array([1, 1])

# Собственные числа
lambda_u = -1
lambda_v = 5

# Проверка уравнения для собственного вектора u
result_u = np.dot(F, u)
expected_u = lambda_u * u

print("Проверка для u:")
print("Результат:", result_u)
print("Ожидаемый результат:", expected_u)

# Проверка уравнения для собственного вектора v
result_v = np.dot(F, v)
expected_v = lambda_v * v

print("\nПроверка для v:")
print("Результат:", result_v)
print("Ожидаемый результат:", expected_v)

Проверка для u:
Результат: [-1 -1]
Ожидаемый результат: [-1 -1]

Проверка для v:
Результат: [ 5 10]
Ожидаемый результат: [ 5 10]


In [46]:
# Матрица F
F = np.array([
    [5, 1],
    [1, 5]
])
# Находим собственные значения и векторы
eigenvalues, eigenvectors = np.linalg.eig(F)

# Выводим результаты
print("Собственные значения:", eigenvalues)
print("Собственные векторы:\n", eigenvectors)

Собственные значения: [6. 4.]
Собственные векторы:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [47]:
# создаем матрицу А
A = np.array([
    [3, 1],
    [2, 2]
]).T
# вычисляем собственные числа и собственные векторы
eig_values, eig_vectors = np.linalg.eig(A)
print('Собственные числа: \n', eig_values)
print('Собственные векторы: \n', eig_vectors)

Собственные числа: 
 [4. 1.]
Собственные векторы: 
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [48]:
# создаем матрицу А
A = np.array([
    [1, -5, -6],
    [4, 8, 7],
    [5, 9, 11]
]).T
# вычисляем собственные числа и собственные векторы
eig_values, eig_vectors = np.linalg.eig(A)
print('Собственные числа: \n', eig_values)
print('Собственные векторы: \n', eig_vectors)

Собственные числа: 
 [13.59373746  5.03209301  1.37416954]
Собственные векторы: 
 [[ 0.45145779  0.83661458  0.10258363]
 [ 0.62348353  0.44632316 -0.77299039]
 [ 0.63832135  0.31760303  0.62606905]]


In [49]:
# создаем матрицу А
A = np.array([
    [1, -4, -5, -6],
    [4, 12, 8, 7],
    [5, 14, 9, 11],    [8, 15, 7, 4]
]).T
# вычисляем собственные числа и собственные векторы
eig_values, eig_vectors = np.linalg.eig(A)
print('Собственные числа: \n', eig_values)
print('Собственные векторы: \n', eig_vectors)

Собственные числа: 
 [ 2.54687092e+01  1.53129080e+00  1.63252001e-14 -1.00000000e+00]
Собственные векторы: 
 [[-0.33176532 -0.6739195   0.5479715  -0.5312532 ]
 [-0.75622544 -0.67703635  0.72006173 -0.64930947]
 [-0.42446012 -0.00311685 -0.00452869 -0.11805627]
 [-0.37133334  0.2957103  -0.42569687  0.5312532 ]]


In [50]:
# создаем матрицу А
A = np.array([
    [0, 1],
    [-1, 0],
]).T
# вычисляем собственные числа и собственные векторы
eig_values, eig_vectors = np.linalg.eig(A)
print('Собственные числа: \n', eig_values)
print('Собственные векторы: \n', eig_vectors)

Собственные числа: 
 [0.+1.j 0.-1.j]
Собственные векторы: 
 [[0.70710678+0.j         0.70710678-0.j        ]
 [0.        -0.70710678j 0.        +0.70710678j]]
