In [1]:
import numpy as np

In [2]:
s = np.array([33, 65, 50, 45])
s
## array([33, 65, 50, 45])

array([33, 65, 50, 45])

In [3]:
s[2]
## 50

np.int64(50)

In [4]:
len(s)
## 4

4

In [5]:
t = np.array([12, 14, 17, 19, 24, 28, 31, 31, 27, 22, 17, 13])

In [6]:
t[6]

np.int64(31)

In [7]:
t.min()

np.int64(12)

In [8]:
a = np.array([10, 8, 5, 1])
b = np.array([5, 15, 9, 7])
a + b
## array([15, 23, 14,  8])
a - b
## array([ 5, -7, -4, -6])

array([ 5, -7, -4, -6])

In [9]:
a = np.array([120, 45, 68])
omega = 0.2
c = a * omega
c
## array([24. ,  9. , 13.6])

array([24. ,  9. , 13.6])

In [10]:
a = np.array([120, 150, 190])
b = np.array([130, 130, 130])
c = np.array([2, 3, 2.5])
cur = 72
r1 = c * cur
print(r1)


[144. 216. 180.]


In [11]:
r2 = a + b + r1
print(r2)


[394. 496. 500.]


In [12]:
x = np.array([4, 5])
y = np.array([2, 1])
u = np.array([1, 0])
r = x*2+y*-3+u*5
print(r)



[7 7]


In [13]:
x = np.array([3, 4, 5, 9])
y = np.array([1, 5, 3, 6])
r1 = x*200
r2 = y*400
r3 = r2-r1
print(r3)


[-200 1200  200  600]


In [14]:
a = np.array([65, 70, 120, 30])
w = np.array([0.4, 0.4, 0.2, 0.8])
np.dot(a, w)

np.float64(102.0)

In [15]:
a = np.array([4, 5, -1])
w = np.array([2, 0, 1])
np.dot(a, w)

np.int64(7)

In [16]:
import numpy as np
v1 = np.array([1,2,3,1])
v2 = np.array([4,5,6,1])
v3 = np.array([7,8,9,1])
A = np.array([v1, v2, v3]).T
print(np.linalg.matrix_rank(A))

2


In [17]:
v1 = np.array([1,2,3,1])
v2 = np.array([4,5,6,1])
v3 = np.array([7,8,10,1])
A = np.array([v1, v2, v3]).T
print(np.linalg.matrix_rank(A))
# 3

3


In [18]:
v1 = np.array([4,1,0])
v2 = np.array([-1,4,0])
v3 = np.array([0,0,1])
A = np.array([v1, v2, v3]).T
print(np.linalg.matrix_rank(A))

3


In [19]:
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])
A = np.array([v1, v2, v3, v4]).T
print(np.linalg.matrix_rank(A))

4


In [20]:
print('Матрица Грама:\n',A.T@A)

Матрица Грама:
 [[360  96  73 -35]
 [ 96  46  16   4]
 [ 73  16  33   4]
 [-35   4   4  51]]


In [21]:
print('Определитель матрицы Грама:\n',np.linalg.det(A.T@A))

Определитель матрицы Грама:
 3716647.9999999995


In [24]:
# Вычисляем определитель матрицы Грама
G = A.T@A
det_G = np.linalg.det(G)
print('det(G):\n',det_G)

det(G):
 3716647.9999999995


In [26]:
# Проверка на вырожденность
is_degenerate = det_G == 0

In [27]:
print("Матрица Грама:\n", G)
print("Определитель матрицы Грама:", det_G)
print("Является ли матрица Грама вырожденной?", is_degenerate)

Матрица Грама:
 [[360  96  73 -35]
 [ 96  46  16   4]
 [ 73  16  33   4]
 [-35   4   4  51]]
Определитель матрицы Грама: 3716647.9999999995
Является ли матрица Грама вырожденной? False


In [28]:
print('Обратная к матрице Грама:\n',np.linalg.inv(G))

Обратная к матрице Грама:
 [[ 0.01711488 -0.02798543 -0.02623063  0.01599775]
 [-0.02798543  0.071967    0.03031441 -0.02722776]
 [-0.02623063  0.03031441  0.07683106 -0.02640498]
 [ 0.01599775 -0.02722776 -0.02640498  0.03479318]]


In [30]:
# Определение векторов
v1 = np.array([-1, 2, -7, 9]).T 
v2 = np.array([2, 8, 2, -1]).T  
dot_product = np.dot(v1, v2)
print(dot_product)

-9


In [31]:
A=np.array([[1,1],[1,2]])
A

array([[1, 1],
       [1, 2]])

In [32]:
G = A.T@A
print("Матрица Грама:\n", G)

Матрица Грама:
 [[2 3]
 [3 5]]


In [33]:
A=np.array([[1,2],[3,7]])
A

array([[1, 2],
       [3, 7]])

In [35]:
print(np.linalg.inv(A))

[[ 7. -2.]
 [-3.  1.]]


In [41]:
# Определение векторов
v1 = np.array([2, 10, -2]).T 
v2 = np.array([3, 2, -2]).T  
v3 = np.array([8, 14, -6]).T  
A = np.array([v1, v2, v3])
print(A)

[[ 2 10 -2]
 [ 3  2 -2]
 [ 8 14 -6]]


In [ ]:
print('Ранг матрицы Грама:\n',np.linalg.matrix_rank(A.T@A))

Ранг матрицы Грама:
 2


In [56]:
v1 = np.array([4, 7, 20])
v2 = np.array([5, 10, 30])
Ab = np.array([v1, v2])
Ab

array([[ 4,  7, 20],
       [ 5, 10, 30]])

In [57]:
v1 = np.array([4, 7])
v2 = np.array([5, 10])
A = np.array([v1, v2])
A

array([[ 4,  7],
       [ 5, 10]])

In [58]:
b = np.array([[20], [30]])
b

array([[20],
       [30]])

In [60]:
inverse_matrix = np.linalg.inv(A)
inverse_matrix

array([[ 2. , -1.4],
       [-1. ,  0.8]])

In [61]:
r = inverse_matrix@b
r

array([[-2.],
       [ 4.]])

In [63]:
# Получение совмещенной матрицы
combined_matrix = np.column_stack((A, b))
combined_matrix

array([[ 4,  7, 20],
       [ 5, 10, 30]])

In [64]:
v1 = np.array([4, 7, -1])
v2 = np.array([-4, 2, 5])
v3 = np.array([0, 9, 4])
A = np.array([v1, v2, v3])
A

array([[ 4,  7, -1],
       [-4,  2,  5],
       [ 0,  9,  4]])

In [66]:
b = np.array([[7], [3], [10]])
b

array([[ 7],
       [ 3],
       [10]])

In [65]:
print('Ранг:\n',np.linalg.matrix_rank(A))

Ранг:
 2


In [67]:
combined_matrix = np.column_stack((A, b))
combined_matrix

array([[ 4,  7, -1,  7],
       [-4,  2,  5,  3],
       [ 0,  9,  4, 10]])

In [68]:
print('Ранг:\n',np.linalg.matrix_rank(combined_matrix))

Ранг:
 2


In [ ]:
import numpy as np
v1 = np.array([1, -5])
v2 = np.array([2, 1])
v3 = np.array([1, 1])
A = np.array([v1, v2, v3])
A

array([[ 1, -5],
       [ 2,  1],
       [ 1,  1]])

In [3]:
b = np.array([[1], [2], [2]])
b

array([[1],
       [2],
       [2]])

In [5]:
ww = np.array([[1], [1]])
ww

array([[1],
       [1]])

In [6]:
bb = A@ww
bb

array([[-4],
       [ 3],
       [ 2]])

In [7]:
e = b-bb
e

array([[ 5],
       [-1],
       [ 0]])

In [8]:
v1 = np.array([1, 2])
v2 = np.array([-3, 1])
v3 = np.array([1, 2])
v4 = np.array([1, -1])
A = np.array([v1, v2, v3, v4])
A

array([[ 1,  2],
       [-3,  1],
       [ 1,  2],
       [ 1, -1]])

In [9]:
b = np.array([[1], [4], [5], [0]])
b

array([[1],
       [4],
       [5],
       [0]])

In [11]:
G = A.T@A
G

array([[12,  0],
       [ 0, 10]])

In [13]:
inverse_matrix = np.linalg.inv(G)
inverse_matrix

array([[0.08333333, 0.        ],
       [0.        , 0.1       ]])

In [16]:
c = A.T@b
c

array([[-6],
       [16]])

In [17]:
bb = inverse_matrix@c
bb

array([[-0.5],
       [ 1.6]])

In [18]:
bb.T

array([[-0.5,  1.6]])