In [1]:
import numpy as np
import pandas as pd #для анализа и предобработки данных

In [2]:
# произведение матриц
A=np.random.randint(5, 12, (3,3))
B=np.random.randint(-2, 4, (3,3))

In [3]:
A

array([[ 9,  8,  5],
       [ 7, 11,  5],
       [11,  7,  9]], dtype=int32)

In [4]:
B

array([[ 0,  0, -2],
       [ 1,  2,  3],
       [ 0,  1,  2]], dtype=int32)

In [5]:
# Поэлементное умножение
A*B

array([[  0,   0, -10],
       [  7,  22,  15],
       [  0,   7,  18]], dtype=int32)

In [6]:
# тип np.matrix
A_m=np.matrix(A)
B_m=np.matrix(B)
print(A_m*B_m)

[[ 8 21 16]
 [11 27 29]
 [ 7 23 17]]


In [7]:
# Матричное умножение
np.dot(A,B)

array([[ 8, 21, 16],
       [11, 27, 29],
       [ 7, 23, 17]], dtype=int32)

In [8]:
# Матричное умножение
A@B

array([[ 8, 21, 16],
       [11, 27, 29],
       [ 7, 23, 17]], dtype=int32)

In [9]:
# Порядок умножения AB != BA
B@A

array([[-22, -14, -18],
       [ 56,  51,  42],
       [ 29,  25,  23]], dtype=int32)

In [10]:
# Умножение прямоугольных матриц возможно не в любом порядке
A=np.random.randint(5, 12, (3,5))
B=np.random.randint(-2, 4, (5,2))
print('A:\n',A)
print('B:\n',B)

A:
 [[ 5  9  8  9  6]
 [10  7  7 11  5]
 [ 9 11  7 11  5]]
B:
 [[ 1 -1]
 [ 2  2]
 [-2  3]
 [ 2 -1]
 [ 0  2]]


In [11]:
# Умножение прямоугольных матриц возможно не в любом порядке
A@B

array([[25, 40],
       [32, 24],
       [39, 33]], dtype=int32)

In [12]:
# Умножение прямоугольных матриц возможно не в любом порядке
B@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [ ]:
# размер произведения матриц
print('shape of A:', np.shape(A))
print('shape of B:', np.shape(B))
print('shape of AB:', np.shape(A@B))

shape of A: (3, 5)
shape of B: (5, 2)
shape of AB: (3, 2)


In [ ]:
# умножение на специальные матрицы
A=np.random.randint(-4, 4, (4,4))
D=np.diag([1,2,0,-1])
print('A:\n',A)
print('D:\n',D)
print('AD:\n',A@D)
print('DA:\n',D@A)

A:
 [[ 0 -3 -1  2]
 [ 2  0 -2 -4]
 [-4 -1 -1 -1]
 [ 2  1 -3  0]]
D:
 [[ 1  0  0  0]
 [ 0  2  0  0]
 [ 0  0  0  0]
 [ 0  0  0 -1]]
AD:
 [[ 0 -6  0 -2]
 [ 2  0  0  4]
 [-4 -2  0  1]
 [ 2  2  0  0]]
DA:
 [[ 0 -3 -1  2]
 [ 4  0 -4 -8]
 [ 0  0  0  0]
 [-2 -1  3  0]]


In [ ]:
# умножение на одномерный массив numpy
A=np.array([[1,0,1],[1,1,1]])
b=np.array([-3,4,5])
A@b

array([2, 6])

In [ ]:
b@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [ ]:
# матрица Грама ортогональной системы векторов
x=np.array([1,1,1])
y=np.array([1,0,-1])
z=np.array([-1,2,-1])
A=np.array([x,y,z])
print (A, type(A))

[[ 1  1  1]
 [ 1  0 -1]
 [-1  2 -1]] <class 'numpy.ndarray'>


In [ ]:
# матрица Грама ортогональной системы векторов
A@A.T

array([[3, 0, 0],
       [0, 2, 0],
       [0, 0, 6]])

In [ ]:
# матрица Грама ортонормированной системы векторов
x_norm=x/np.linalg.norm(x)
y_norm=y/np.linalg.norm(y)
z_norm=z/np.linalg.norm(z)
A_norm=np.array([x_norm,y_norm,z_norm])
print (A_norm, type(A_norm))

[[ 0.57735027  0.57735027  0.57735027]
 [ 0.70710678  0.         -0.70710678]
 [-0.40824829  0.81649658 -0.40824829]] <class 'numpy.ndarray'>


In [ ]:
# матрица Грама ортонормированной системы векторов
A_norm@A_norm.T

array([[ 1.00000000e+00, -1.77961928e-17,  1.66584120e-17],
       [-1.77961928e-17,  1.00000000e+00, -2.45142679e-17],
       [ 1.66584120e-17, -2.45142679e-17,  1.00000000e+00]])

In [ ]:
# ортонормированные системы рулят! :)
np.round(A_norm@A_norm.T,1)

array([[ 1., -0.,  0.],
       [-0.,  1., -0.],
       [ 0., -0.,  1.]])

In [ ]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])

In [ ]:
A

array([[ 5, -1,  3,  1,  2],
       [-2,  8,  5, -1,  1]])

In [ ]:
x

array([1, 2, 3, 4, 5])

In [ ]:
A@x

array([26, 30])

In [ ]:
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])

In [ ]:
B@A

array([[  2,   9,  11,  14],
       [  8, -10, -14, -11]])

In [ ]:
# Определяем векторы
x = np.array([1, 2, 1, 0, 4])
y = np.array([2, 1, -1, 1, 0])
z = np.array([-1, 1, -1, 0, 0])

# Создаем матрицу из векторов
A = np.array([x, y, z])

# Вычисляем матрицу Грама
G = np.dot(A, A.T)

# Выводим матрицу Грама
print("Матрица Грама:")
print(G)

Матрица Грама:
[[22  3  0]
 [ 3  7  0]
 [ 0  0  3]]


In [ ]:
A

array([[ 1,  2,  1,  0,  4],
       [ 2,  1, -1,  1,  0],
       [-1,  1, -1,  0,  0]])

In [ ]:
A.T@A

array([[ 6,  3,  0,  2,  4],
       [ 3,  6,  0,  1,  8],
       [ 0,  0,  3, -1,  4],
       [ 2,  1, -1,  1,  0],
       [ 4,  8,  4,  0, 16]])

In [ ]:
Count_DF = pd.DataFrame({
    'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
    'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
    'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
    'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
    'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)
Price_DF = pd.DataFrame({
    'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
    'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
    'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
    'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
    'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)

In [ ]:
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])

In [ ]:
# Вычисление общего дохода для каждого стилиста
# Общее количество дохода по всем услугам
revenue = (Count_DF * Price_DF).sum(axis=1)

# Общий доход с учетом комиссий
commissioned_revenue = revenue * com.sum() 

print(commissioned_revenue)

Аня       55.35
Борис     81.09
Вика      63.90
Галя      79.56
Дима     187.65
Егор     121.50
Женя      69.93
Юра      176.40
dtype: float64


In [ ]:
A = Count_DF.values
B = Price_DF.values

In [ ]:
C = A * B
C

array([[20. ,  7.5, 12. , 12. , 10. ],
       [ 3.6, 52.5,  3. , 25. ,  6. ],
       [24. , 24. ,  0. , 15. ,  8. ],
       [ 7.2,  9.6, 50.4, 11.2, 10. ],
       [15. , 87.5, 54. , 25. , 27. ],
       [50. , 15. ,  6. , 34. , 30. ],
       [24.2,  1. ,  6. , 12.5, 34. ],
       [31.5,  0. , 77.5, 31. , 56. ]])

In [ ]:
D = C@com
D

array([11.3 , 15.22, 11.9 , 20.6 , 41.9 , 21.2 , 11.49, 38.25])

In [ ]:
E = np.array([1, 1, 1, 1, 1])

In [ ]:
S = C@E
S

array([ 61.5,  90.1,  71. ,  88.4, 208.5, 135. ,  77.7, 196. ])

In [ ]:
S - D

array([ 50.2 ,  74.88,  59.1 ,  67.8 , 166.6 , 113.8 ,  66.21, 157.75])

In [ ]:
A = np.matrix('1,2,3; 4,5,6; 7, 8, 10')
A

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8, 10]])

In [ ]:
np.linalg.inv(A)

matrix([[-0.66666667, -1.33333333,  1.        ],
        [-0.66666667,  3.66666667, -2.        ],
        [ 1.        , -2.        ,  1.        ]])

In [ ]:
A = np.matrix('1,2; 2,5')

In [ ]:
np.linalg.inv(A)

matrix([[ 5., -2.],
        [-2.,  1.]])

In [ ]:
A = np.matrix('2,0,0; 0,4,0; 0, 0, 5')
A

matrix([[2, 0, 0],
        [0, 4, 0],
        [0, 0, 5]])

In [ ]:
np.linalg.inv(A)

matrix([[0.5 , 0.  , 0.  ],
        [0.  , 0.25, 0.  ],
        [0.  , 0.  , 0.2 ]])

In [13]:
A = np.matrix ("1, 2, 3; 4, 5, 6 ; 7, 8, 10")
print(np.linalg.det(A))
# -3.0000000000009

-2.9999999999999996


In [15]:
A = np.matrix ("1, 2; 1, 1")
A

matrix([[1, 2],
        [1, 1]])

In [16]:
B = np.matrix ("5, -2; -1, 4")
B

matrix([[ 5, -2],
        [-1,  4]])

In [17]:
print(np.linalg.det(A))
print(np.linalg.det(B))
print(np.linalg.det(A+B))

-1.0
17.999999999999996
29.99999999999999


In [18]:
A = np.matrix ("2, 0, 0; 0, 1, 0 ; 0, 0, 4")
print(np.linalg.det(A))

7.999999999999998


In [19]:
print(np.linalg.det(A.T))

7.999999999999998


In [20]:
1/8

0.125