In [1]:
import numpy as np

In [2]:
f = np.array([3, 7, 14, 23, 36, 47], dtype=float)
 
np.gradient(f)

# array([ 4. ,  5.5,  8. , 11. , 12. , 11. ])

array([ 4. ,  5.5,  8. , 11. , 12. , 11. ])

In [3]:
print(f[1] - f[0], f[-1] - f[-2])

4.0 11.0


In [4]:
(f[2] - f[0])/2 # 5.5
(f[3] - f[1])/2 # 8.0
(f[4] - f[2])/2 # 11.0
(f[5] - f[3])/2 # 12.0

np.float64(12.0)

In [6]:
np.gradient(f, 2)

# array([2.  , 2.75, 4.  , 5.5 , 6.  , 5.5 ])

for i in range(1, len(f) - 1):
    print((f[i + 1] - f[i - 1])/(2*2))

2.75
4.0
5.5
6.0


In [8]:
import sympy as sp
# Определяем переменные
a, b = sp.symbols('a b')

# Определяем функцию
f = (5 - a - 2*b)**2

# Вычисляем частные производные
df_da = sp.diff(f, a)
df_db = sp.diff(f, b)

# Вычисляем градиент в точке M(1, 1)
point = (1, 1)
gradient_at_M = (df_da.subs({a: point[0], b: point[1]}), df_db.subs({a: point[0], b: point[1]}))

# Выводим результат
print("Градиент в точке M(1, 1):", gradient_at_M)

Градиент в точке M(1, 1): (-4, -8)


In [12]:
import sympy as sp

# Определяем переменные
w0, w1 = sp.symbols('w0 w1')

# Определяем функцию L
L = (2.1 - w0 - w1)**2 + (2.9 - w0 - 3*w1)**2 + (4.1 - w0 - 5*w1)**2

# Вычисляем частные производные
dL_dw0 = sp.diff(L, w0)
print(dL_dw0)
dL_dw1 = sp.diff(L, w1)
print(dL_dw1)

# Устанавливаем градиент в ноль
grad_eqs = [dL_dw0, dL_dw1]
print(grad_eqs)

# Решаем систему уравнений
solutions = sp.solve(grad_eqs, (w0, w1))
print(solutions)


6.0*w0 + 18.0*w1 - 18.2
18.0*w0 + 70.0*w1 - 62.6
[6.0*w0 + 18.0*w1 - 18.2, 18.0*w0 + 70.0*w1 - 62.6]
{w0: 1.53333333333333, w1: 0.500000000000000}


In [18]:
f = np.array([8, 2, 8, 3, 5, 6, 5, 15], dtype=float)
 
f_grad = np.gradient(f, 7)
print(f_grad[7])



1.4285714285714286
